language: bash
services: docker
before_install:
  - cd RestWithSpringBootDocker\ Docker/
  - echo "We area in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push leoafj/mysql-rest-with-spring-boot;
    docker push leoafj/rest-with-spring-boot;
  on:
    branch: main
notifications:
  email: false
    
